---
title: "u.s. incarceration data"
output:
  html_document:
    df_print: paged
---

(data from [The Vera Institute](https://github.com/vera-institute/incarceration_trends) in 2015)

```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
library(knitr)
library(RColorBrewer)

theme_set(theme_fivethirtyeight())

incarcerations <- tibble(read.csv("incarceration_trends.csv"))
prison_summary <- tibble(read.csv("prison_summary.csv"))
```

### overall incarcerations

```{r overall, echo=FALSE, fig.width=10, fig.height=7.5}
incarcerations %>%
    group_by(year) %>% 
    summarise(prison=sum(total_prison_pop,na.rm=TRUE),
              jail=sum(total_jail_pop,na.rm=TRUE),
              .groups="drop"
              ) %>% 
    filter(year %in% seq(1983,2015)) %>% 
    ggplot(aes(x=year)) +
        geom_line(aes(y=prison,color="prison"),size=1.5) +
        geom_line(aes(y=jail,color="jail"),size=1.5) +
        xlab("") + ylab("total") +
        ggtitle("u.s. prison and jail populations") +
        scale_color_brewer(palette="Set1") +
        scale_y_continuous(labels=scales::comma) +
        theme(legend.title=element_blank())
```

### incarcerations by race

```{r overall_race, echo=FALSE, fig.width=10, fig.height=7.5}
demog <- incarcerations %>%
    group_by(year) %>% 
    summarise(black=sum(black_prison_pop,na.rm=TRUE),
              asian=sum(asian_prison_pop,na.rm=TRUE),
              latino=sum(latino_prison_pop,na.rm=TRUE),
              native=sum(native_prison_pop,na.rm=TRUE),
              other=sum(other_prison_pop,na.rm=TRUE),
              white=sum(white_prison_pop,na.rm=TRUE),
              .groups="drop"
              ) %>% 
    filter(year %in% seq(1983,2015)) %>% 
    pivot_longer(cols="black":"white",names_to="demographic")

demog %>% 
    ggplot(aes(x=year)) +
        geom_line(aes(y=value,color=demographic),size=1.5) +
        xlab("") + ylab("total") +
        scale_y_continuous(labels=scales::comma) +
        labs(title="u.s. prison population", subtitle="(totals)") +
        facet_wrap(~demographic,nrow=2) +
        theme(legend.position="none", legend.title=element_blank()) +
        scale_color_brewer(palette="Set1")
```


```{r incarceration_rates, echo=FALSE, fig.width=10, fig.height=7.5}
prison_summary %>% 
    group_by(pop_category,year) %>% 
    filter(pop_category %in% c("Black","White","Asian","Other","Native American","Latino"),
           year>=1990
           ) %>% 
    summarise(avg=mean(rate_per_100000),.groups="drop") %>% 
    ggplot(aes(x=year,y=avg,color=pop_category)) +
        geom_line(size=1.5) +
        xlab("") + ylab("incarcerations per 100,000") +
        scale_y_continuous(labels=scales::comma) +
        labs(title="average incarceration rates", subtitle="(per 100,000)") +
        theme(legend.title=element_blank()) +
        scale_color_brewer(palette="Set1")
```

### black incarcerations

```{r black_pop, echo=FALSE, fig.width=10, fig.height=7.5}
incarcerations %>%
    group_by(year,region) %>% 
    filter(!is.na(black_prison_pop)) %>% 
    summarise(total_black=sum(black_prison_pop),.groups="drop") %>% 
    ggplot(aes(x=year,y=total_black,color=region)) +
        geom_line(size=1.5) +
        scale_color_brewer(palette="Set2") +
        xlab("") + ylab("total") +
        scale_y_continuous(labels=scales::comma) +
        theme(legend.title=element_blank()) +
        labs(title="u.s. black prison population", subtitle="(by region)")

# top by state
#incarcerations %>%
#    filter(year==2010) %>% 
#    group_by(year,state) %>% 
#    summarise(total_black=sum(black_prison_pop,na.rm=TRUE),.groups="drop") %>% 
#    arrange(desc(total_black)) %>% 
#    top_n(4,total_black) %>% 
#    kable()

# chart by state
#incarcerations %>%
#    group_by(year,state) %>% 
#    filter(!is.na(black_prison_pop),state %in% c("TX","FL","CA","GA")) %>% 
#    summarise(total=sum(black_prison_pop),.groups="drop") %>% 
#    ggplot(aes(x=year,y=total,color=state)) +
#        geom_line(size=1.5) +
#        scale_color_brewer(palette="Set1") +
#        xlab("") + ylab("total") +
#        scale_y_continuous(labels=scales::comma) +
#        theme(legend.title=element_blank()) +
#        ggtitle("u.s. black prison population")

```