---
title: "acts"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(RMariaDB)
library(tidyquery)
```

```{r data, echo=FALSE}
transactions <- read_csv("~/repos/code/acts/.data_2204152117")
```


```{r clean, echo=FALSE}
transactions <- transactions %>% 
  mutate(
    date = mdy(Date),
    description = Description,
    original = `Original Description`,
    amount = Amount,
    type = `Transaction Type`,
    category = Category,
    account = `Account Name`
  ) %>% 
  select(
    # remove renamed columns
    -Date,
    -Description,
    -'Original Description',
    -Amount,
    -'Transaction Type',
    -Category,
    -'Account Name',
    # remove useless columns
    -Labels,
    -Notes
  )
```


```{r database_tools, echo=FALSE}
db <- dbConnect( # connect to remote Clever Cloud database
  RMariaDB::MariaDB(),
  user = "uregdz06i7ou4d65",
  password = "q6sGFI1tu1fsAvIPVFQh",
  host = "b28kw3czffvrcmddjxri-mysql.services.clever-cloud.com",
  port = 3306,
  dbname = "b28kw3czffvrcmddjxri"
)

# SQL connection interface terminal — local dataframe
query(
  early_transactions,
  "
    select min(date), max(date)
  "  
)
          
# SQL connection interface terminal — remote database
dbGetQuery(
  db,
  "
    create table transactions (
      date date,
      description varchar(128),
      original varchar(128),
      amount double(12,2),
      type varchar(32),
      category varchar(128),
      account varchar(128)
    )
  "
)

dbCreateTable(
  db,
  "transactions",
  transactions
) 

dbWriteTable(
  db,
  "transactions",
  transactions,
  append = TRUE
)
```

```{r analysis, echo=FALSE}
dbGetQuery(
  db,
  "
    select 
        sq.year as year, sq.month as month, sum(sq.amount) as expenses
    from
        (
          select 
              *,
      		extract(year from date) as year,
      		extract(month from date) as month
          from
              transactions
          where
              type like 'debit'
     			and
              (
                category in ('restaurants', 'coffee shops')
         	    		or
     	        	category regexp 'food'
     			        or
     		        category regexp 'alcohol'
              )
    	  ) as sq
    group by sq.year , sq.month
    order by sq.year desc, sq.month desc;
  "
)
```
