---
title: "Corbin & Co. Employee Survey Program"
output: html_notebook
---

```{r}
library(DBI)
library(tidyverse)
library(ggthemes)
library(RColorBrewer)
```

```{r echo = TRUE, show = TRUE}
# connect to Clever Cloud survey database
db <- dbConnect(
  RMySQL::MySQL(),
  dbname = "b28kw3czffvrcmddjxri",
  host = "b28kw3czffvrcmddjxri-mysql.services.clever-cloud.com",
  port = 3306,
  user = "uregdz06i7ou4d65",
  password = "q6sGFI1tu1fsAvIPVFQh"
)

dbListTables(db)

```

```{r echo = TRUE, show = TRUE}
# generate report using dplyr
survey_data <- dbReadTable(db, "employee_survey")
employee_data <- dbReadTable(db, "employee")

# need to do a left join of the employee data to the survey data frame using employeeID
comb_survey_data <- survey_data %>% 
  left_join(
    employee_data,
    by = 'employeeID'
  )

# generate department results table
dep_results <- comb_survey_data %>% 
  group_by(
    department,
    date
  ) %>% 
  summarise(
    'count' = n(),
    'Qavg1' = mean(question1),
    'Qavg2' = mean(question2),
    'Qavg3' = mean(question3),
    'Qavg4' = mean(question4),
    'Qavg5' = mean(question5),
    .groups = 'drop'
  )

dep_results
  
```

```{r echo = TRUE, show = TRUE}
# generate report using SQL

# need to do a left join of the employee data to the survey data frame using employeeID
data <- dbGetQuery(db,
                   "
                   SELECT *
                   FROM employee_survey
                   LEFT JOIN employee ON employee_survey.employeeID = employee.employeeID
                   ;
                   "
                  )

data

# calculate aggregate data

# (method 1)
#dbSendQuery(db, # create temporary table with joined results
#                   "
#                   CREATE TEMPORARY TABLE comb_survey
#                      SELECT employee_survey.*, employee.name, employee.department
#                      FROM employee_survey
#                      LEFT JOIN employee ON employee_survey.employeeID = employee.employeeID
#                   ;
#                   "
#                  )
#
#results <- dbGetQuery(db,
#                   "
#                   SELECT
#                      department,
#                      date,
#                      COUNT(*) AS 'count',
#                      AVG(question1) AS 'Qavg1',
#                      AVG(question2) AS 'Qavg2',
#                      AVG(question3) AS 'Qavg3',
#                      AVG(question4) AS 'Qavg4',
#                      AVG(question5) AS 'Qavg5'
#                   FROM comb_survey
#                   GROUP BY department, date  
#                   ;
#                   "
#                  )
#results
#
#dbSendQuery(db, # remove temporary table
#                   "
#                   DROP TEMPORARY TABLE comb_survey
#                   ;
#                   "
#                 )

# (method 1)

results <- dbGetQuery(db,
                    "
                      SELECT
                          department,
                          date,
                          AVG(question1) AS 'Qavg1',
                          AVG(question2) AS 'Qavg3',
                          AVG(question3) AS 'Qavg3',
                          AVG(question4) AS 'Qavg4',
                          AVG(question5) AS 'Qavg5'
                      FROM
                          employee_survey s LEFT JOIN employee e
                              ON s.employeeID = e.employeeID
                      GROUP BY
                          department,
                          date
                      ;
                    "
                    )

results

```

```{r echo = TRUE, show = TRUE, fig.width = 12}

comb_survey_data %>% 
  group_by(department, date) %>%
  summarise(
    Safety = mean(question1),
    Depend = mean(question2),
    Clarity = mean(question3),
    Meaning = mean(question4),
    Impact = mean(question5),
    .groups = "drop"
  ) %>% 
  pivot_longer(
    cols = c(
      Safety,
      Depend,
      Clarity,
      Meaning,
      Impact
    ),
    names_to = "question",
    values_to = "avg"
  ) %>% 
  ggplot(
    aes(
      x = date,
      y = avg
    )
  ) +
    geom_col(
      aes(
        fill = department
      ),
      color = "black",
      size = 1.0,
      alpha = 0.9
    ) +
    facet_grid(
      cols = vars(department),
      rows = vars(question)
    ) +
    labs(
      #title = NULL,
      title = "Q1 2001 Corbin & Co. Employee Cross-functional Survey",
      x = "",
      y = "average feedback scores (0-5) for five key dynamics"
    ) +
    theme_economist() +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      legend.position = "none"
    ) +
    scale_fill_brewer(
      palette = "Set2"
    )
    
```

```{r echo = TRUE, show = TRUE, fig.width = 12}

comb_survey_data %>% 
  filter(
    department == "Lab"
  ) %>% 
  group_by(date) %>%
  summarise(
    depend_avg = mean(question2),
    .groups = "drop"
  ) %>% 
  ggplot(
    aes(
      x = date,
      y = depend_avg
    )
  ) +
    geom_col(
      aes(
        
      ),
      fill = "#ffd924",
      color = "black",
      size = 1.0,
      alpha = 0.8
    ) +
    labs(
      #title = NULL,
      title = "Q1 2001 Corbin & Co. Employee Survey — Clinical Laboratory (104)",
      x = "",
      y = "Dependability Rating"
    ) +
    theme_economist() +
    theme(
      legend.position = "none"
    )
    
```
