---
title: "db"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
library(RMariaDB)
library(lubridate)
```

```{r data}
fastrak_df <- read_csv("/Users/dedmonds/sb/code/code/fastrak/FasTrak_transaction_report_220404_21Oct-22Apr.csv")

# data cleaning
fastrak_df <- fastrak_df %>%
  select('POSTED DATE':'BALANCE') %>% 
  mutate(
    # convert numeric columns from character strings
    BALANCE = as.numeric(str_replace(fastrak_df$BALANCE, "\\$", "")),
    DEBIT = as.numeric(str_replace(fastrak_df$`DEBIT(-)`, "\\$", "")),
    CREDIT = as.numeric(str_replace(fastrak_df$`CREDIT(+)`, "\\$", "")),
    `ENTRY LANE` = as.numeric(`ENTRY LANE`),
    `EXIT LANE` = as.numeric(`EXIT LANE`),
    # convert data columns from character strings
    `POSTED DATE` = mdy(`POSTED DATE`),
    `TRANSACTION DATE` = mdy(`TRANSACTION DATE`),
    `ENTRY DATE/TIME` = mdy_hms(fastrak_df$`ENTRY DATE/TIME`, tz = "US/Pacific")
  ) %>% 
  select(
    -`DEBIT(-)`,
    -`CREDIT(+)`,
  )
  

str(fastrak_df)
```

```{r dbconnect}
library_db <- dbConnect(
        MariaDB(),
        dbname = "b28kw3czffvrcmddjxri",
        host = "b28kw3czffvrcmddjxri-mysql.services.clever-cloud.com",
        port = 3306,
        user = "uregdz06i7ou4d65",
        password = "q6sGFI1tu1fsAvIPVFQh"
      )

dbListTables(library_db)
```

```{r dbedit}

#dbCreateTable(library_db, "fastrak", fastrak_df)

dbWriteTable(library_db, "fastrak", fastrak_df, overwrite = TRUE, row.names = FALSE)

data <- dbGetQuery(
  library_db,
  "
    select *
    from fastrak
    ;
  "
)

#dbRemoveTable(library_db, "fastrak")
dbDisconnect(library_db)

```
